88 mark favorites
DataManagementLab/ThesisPortal pull request #102
Opened 2023-01-18 14:57 UTC by Arne815

2023-01-18 15:18 UTC, netcodedev requested changes

2023-01-18 15:18 UTC, netcodedev commented on src/routes/profile/+page.server.js
> +	}
stattdessem die function map benutzen:

```js
let favorites = (await db.query('SELECT * FROM favorite WHERE student=$student FETCH topic' ,{
		student: `student:${locals.session.cas.user}`
	}))[0].result;

favorites = favorites.map(elem => elem.topic)
```

2023-01-18 15:18 UTC, netcodedev commented on src/routes/profile/+page.server.js
> +		isEmployee: affiliation[0]._text == 'employee' || affiliation[1]._text == 'employee'
`isEmployee` ist bereits durch https://github.com/DataManagementLab/ThesisPortal/blob/main/src/routes/%2Blayout.server.js verfügbar, muss hier nicht erneut definiert werden

2023-01-18 15:29 UTC, t1md0e approved these changes

2023-01-18 18:22 UTC, netcodedev approved these changes

2023-01-19 14:04 UTC, Serena290 approved these changes

2023-01-19 14:04 UTC, merged