106 delete button
DataManagementLab/ThesisPortal pull request #107
Opened 2023-01-23 15:49 UTC by Arne815

2023-01-23 16:25 UTC, netcodedev requested changes

2023-01-23 16:25 UTC, netcodedev commented on src/lib/components/TopicView.svelte
> +							{/if}
Wenn die das Favorisieren nicht verfügbar sein soll sollte die ganze form nicht angezeigt werden

2023-01-23 16:25 UTC, netcodedev commented on src/lib/components/TopicView.svelte
> +							<h3 class="font-bold text-lg">Bestätigen Sie das Löschen</h3>
Der Text sollte etwas schöner sein, zb:
"Soll dieses Thesis Thema "<hier topic title einfügen" wirklich gelöscht werden?

2023-01-23 16:25 UTC, netcodedev commented on src/routes/overview/+page.svelte
> +	<TopicView data={data.topics} favorites={data.favorites} showFavoriteIcon=true/>
```js
showFavoriteIcon={true}
```
für die consistency

2023-01-24 11:35 UTC, Arne815 commented on src/routes/overview/+page.svelte
> +	<TopicView data={data.topics} favorites={data.favorites} showFavoriteIcon=true/>
ok

2023-01-24 12:49 UTC, netcodedev approved these changes

2023-01-24 15:27 UTC, t1md0e approved these changes

2023-01-25 12:02 UTC, merged

2023-01-25 12:03 UTC, theresab867 approved these changes