implementation finished
DataManagementLab/ThesisPortal pull request #85
Opened 2023-01-12 12:27 UTC by Arne815

2023-01-12 12:51 UTC, netcodedev requested changes

2023-01-12 12:51 UTC, netcodedev commented on src/routes/+layout.svelte
> +			|| data.eduPersonAffiliation[1]._text == "employee"}
Anpassung nach Kommentar in +layout.server.js:
```
{#if data.isEmployee}
```

2023-01-12 20:29 UTC, t1md0e approved these changes

2023-01-13 11:32 UTC, theresab867 approved these changes

2023-01-13 11:34 UTC, merged